services:
  mongo:
    image: mongo:latest
    container_name: hidrored-mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

    networks:
      - hidrored-net

  backend:
    build: ./backend
    container_name: hidrored-backend

    depends_on:
      mongo:
        condition: service_healthy

    ports:
      - "8080:8080"

    networks:
      - hidrored-net
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/hidrored_db

  mongo-express:
    image: mongo-express:latest
    container_name: hidrored-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_BASICAUTH_USERNAME=
      - ME_CONFIG_BASICAUTH_PASSWORD=
    depends_on:
      - mongo
    networks:
      - hidrored-net

networks:
  hidrored-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local
